# Site settings
title: El Noskcäj Living
email: elnoskcaj@gmail.com
description: "El Noskcaj Decor Consultancy, custom made cushions and bedding. Local Hobart consultant."
baseurl: "/ElNoskcaj"
url: "http://elnoskcaj.com.au"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
